In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [2]:
from sklearn.datasets import load_diabetes

In [7]:
data = load_diabetes()

In [8]:
data

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [9]:
data.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [10]:
data.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [11]:
data.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [13]:
df = pd.DataFrame(data.data,columns=data.feature_names)

In [14]:
df

age       sex       bmi        bp        s1        s2        s3   
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401  \
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [16]:
print(data.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

Note: Each of these 1

In [19]:
df['y']=data.target

In [20]:
df

age       sex       bmi        bp        s1        s2        s3   
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401  \
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  Price      y  
0   -0.002592  0.019907 -0.017646  151.0  151.0  
1   -0.039493 -0.068332 -0.092204   75.0   75.0  
2   -0.002592  0.002861 -0.025930  141.0  141.0  
3    0.034309  0.022688 -0.009362  206.0  206.0  
4   -0.002592 -0.031988 -0.046641  135.0  135.0  
..        ...       ...       ...    ...    ...  
437 -0.002592  0.031193  0.007207  178.0  178.0  
438  0.034309 -0.018114  0.044485  104.0  104.0  
439 -0.011080 -0.046883  0.015491  132.0  132.0  
440  0.026560  0.044529 -0.025930  220.0  220.0  
441 -0.039493 -0.004222  0.003064   57.0   57.0  

[442 rows x 12 columns]

In [24]:
X=df[['age','sex','bmi','bp']]

In [25]:
Y=df[['y']]

In [29]:
X

age       sex       bmi        bp
0    0.038076  0.050680  0.061696  0.021872
1   -0.001882 -0.044642 -0.051474 -0.026328
2    0.085299  0.050680  0.044451 -0.005670
3   -0.089063 -0.044642 -0.011595 -0.036656
4    0.005383 -0.044642 -0.036385  0.021872
..        ...       ...       ...       ...
437  0.041708  0.050680  0.019662  0.059744
438 -0.005515  0.050680 -0.015906 -0.067642
439  0.041708  0.050680 -0.015906  0.017293
440 -0.045472 -0.044642  0.039062  0.001215
441 -0.045472 -0.044642 -0.073030 -0.081413

[442 rows x 4 columns]

In [30]:
Y

y
0    151.0
1     75.0
2    141.0
3    206.0
4    135.0
..     ...
437  178.0
438  104.0
439  132.0
440  220.0
441   57.0

[442 rows x 1 columns]

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=100)

In [28]:
X_train

age       sex       bmi        bp
393 -0.074533 -0.044642 -0.046085 -0.043542
265 -0.034575  0.050680 -0.025607 -0.017135
300  0.016281 -0.044642  0.073552 -0.041235
326  0.045341  0.050680 -0.008362 -0.033213
414  0.081666  0.050680  0.006728 -0.004534
..        ...       ...       ...       ...
343 -0.020045 -0.044642  0.018584  0.090729
359  0.038076  0.050680  0.005650  0.032201
323  0.070769  0.050680 -0.007284  0.049415
280  0.009016  0.050680  0.018584  0.039087
8    0.041708  0.050680  0.061696 -0.040099

[309 rows x 4 columns]

In [31]:
y_train

y
393   69.0
265   74.0
300  275.0
326  131.0
414  131.0
..     ...
343  113.0
359  311.0
323  248.0
280  265.0
8    110.0

[309 rows x 1 columns]

In [32]:
model=LinearRegression()

In [33]:
model.fit(X_train,y_train)

LinearRegression()

In [34]:
y_pred = model.predict(X_test)

In [35]:
y_pred

array([[ 90.36344372],
       [ 55.02317964],
       [176.07926441],
       [ 79.66940344],
       [142.94973013],
       [148.37908329],
       [100.9552649 ],
       [213.12956515],
       [115.11943381],
       [221.59898826],
       [174.36972231],
       [191.16957926],
       [228.26819898],
       [227.89269177],
       [ 99.00795014],
       [128.89189111],
       [ 63.8618047 ],
       [121.36223798],
       [190.1896773 ],
       [190.14270892],
       [230.54414859],
       [216.04819864],
       [ 89.99870204],
       [178.78828749],
       [211.13665649],
       [ 91.66659208],
       [286.71818968],
       [131.01797886],
       [180.81254082],
       [169.39656439],
       [139.08853057],
       [178.82223557],
       [128.83436258],
       [ 98.80494587],
       [123.51406309],
       [179.29090911],
       [220.78956373],
       [142.59635675],
       [199.13037736],
       [240.39728774],
       [ 98.91897923],
       [189.58722373],
       [ 75.16143407],
       [144

In [36]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [37]:
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
r2=r2_score(y_test,y_pred)
a_r2=1-(1-r2)*(len(Y)-1)/(len(Y)-X.shape[1]-1)

In [38]:
mae

46.46913222373944

In [39]:
mse

3221.7188287764916

In [42]:
model.predict([[0.038076,	0.050680,	0.061696,	0.021872]])

c:\Users\Hp\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[210.09610459]])