In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df=pd.read_csv('C:\\Users\\Hp\\Downloads\\Advertising.csv')

In [6]:
df

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [8]:
X = df.drop('Sales',axis=1)

In [11]:
y= df[['Sales']]

In [12]:
y

Sales
0     22.1
1     10.4
2      9.3
3     18.5
4     12.9
..     ...
195    7.6
196    9.7
197   12.8
198   25.5
199   13.4

[200 rows x 1 columns]

In [13]:
from sklearn.preprocessing import PolynomialFeatures

In [14]:
polynomial_converter=PolynomialFeatures(degree=2,include_bias=False)

In [15]:
polynomial_converter

PolynomialFeatures(include_bias=False)

In [16]:
poly_features=polynomial_converter.fit_transform(X)

In [17]:
poly_features.shape

(200, 14)

In [19]:
X.shape

(200, 4)

In [20]:
X.iloc[0]

Unnamed: 0      1.0
TV            230.1
Radio          37.8
Newspaper      69.2
Name: 0, dtype: float64

In [21]:
poly_features[0]

array([1.000000e+00, 2.301000e+02, 3.780000e+01, 6.920000e+01,
       1.000000e+00, 2.301000e+02, 3.780000e+01, 6.920000e+01,
       5.294601e+04, 8.697780e+03, 1.592292e+04, 1.428840e+03,
       2.615760e+03, 4.788640e+03])

In [25]:
poly_features[0][:3]

array([  1. , 230.1,  37.8])

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3,random_state=100)

In [29]:
from sklearn.linear_model import LinearRegression

In [30]:
model = LinearRegression(fit_intercept=True)

In [31]:
model.fit(X_train, y_train)

LinearRegression()

In [32]:
test_predictions = model.predict(X_test)

In [33]:
test_predictions

array([[ 7.39281228],
       [21.13802315],
       [17.72204451],
       [20.17813889],
       [22.36167411],
       [12.46599203],
       [12.83318391],
       [11.90443459],
       [22.25870814],
       [22.87413283],
       [11.87699322],
       [20.37819739],
       [ 8.23263525],
       [15.9056069 ],
       [10.30365219],
       [ 9.51319704],
       [17.10040506],
       [12.52369781],
       [18.1941992 ],
       [12.26844365],
       [17.55603103],
       [10.93303512],
       [22.63827932],
       [18.31994992],
       [15.8188868 ],
       [24.30098619],
       [20.32344309],
       [10.76893992],
       [20.94966745],
       [15.45045551],
       [12.96292457],
       [ 9.05923749],
       [11.30754272],
       [15.29389261],
       [ 8.3165958 ],
       [14.37088409],
       [ 9.25690563],
       [12.22468093],
       [12.12934381],
       [15.41515723],
       [17.61472443],
       [14.22092714],
       [15.25950756],
       [12.66879376],
       [12.95746319],
       [10

In [34]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [37]:
mae=mean_absolute_error(y_test,test_predictions)

In [38]:
mae

0.4022499632657198

In [39]:
mse=mean_squared_error(y_test,test_predictions)

In [40]:
mse

0.22458754891000876

In [42]:
score=r2_score(y_test,test_predictions)

In [43]:
score

0.9885760085128541

In [44]:
1-(1-score)*(len(y)-1)/(len(y)-X.shape[1]-1)

0.9883416702259383